name: mycroft
summary: Your AI personal assistant!
description: >
  Mycroft is a free and open-source intelligent personal assistant and knowledge
  navigator for Linux-based operating systems that uses a natural language user
  interface. It is the world’s first fully open-source AI voice assistant.

  Mycroft is named after a fictional computer from 1966 science fiction novel
  "The Moon Is a Harsh Mistress".

  Installing skills by voice seems to be broken for now, but you can use
  the `mycroft.msm` command to list, install, and remove skills.
adopt-info: mycroft
grade: stable
confinement: strict
base: core18

layout:
  /etc/fonts/conf.d:
    bind: $SNAP/etc/fonts/conf.d
  /etc/mycroft/mycroft.conf:
    bind-file: $SNAP/etc/mycroft/mycroft.conf
  /usr/include:
    bind: $SNAP/usr/include
  /usr/bin/aclocal:
    bind-file: $SNAP/usr/bin/aclocal
  /usr/bin/sudo:
    bind-file: $SNAP/usr/bin/sudo
  /usr/lib/git-core:
    bind: $SNAP/usr/lib/git-core
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0/2.10.0/loaders:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0/2.10.0/loaders
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/mpg123:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/mpg123
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/vlc:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/vlc
  /usr/share/aclocal:
    bind: $SNAP/usr/share/aclocal
  /usr/share/git-core:
    bind: $SNAP/usr/share/git-core
  /usr/share/libtool/build-aux:
    bind: $SNAP/usr/share/libtool/build-aux
  /usr/share/perl5:
    bind: $SNAP/usr/share/perl5
  /usr/share/swig3.0:
    bind: $SNAP/usr/share/swig3.0
  /opt/mycroft:
    bind: $SNAP_COMMON/mycroft

hooks:
  install:
    plugs: [network]
  post-refresh:
    plugs: [network]

environment:
  PYTHONPATH: "$SNAP/lib:$SNAP/usr/lib"

apps:
  mycroft:
    command: mycroft-launch
    plugs:
    - alsa
    - mount-observe
    - network
    - network-bind
    - pulseaudio

  mycroftd:
    command: mycroft-launch
    daemon: simple
    plugs:
    - alsa
    - mount-observe
    - network
    - network-bind
    - pulseaudio

parts:
  alsa:
    plugin: nil
    source: https://github.com/diddledan/snapcraft-alsa.git
    # override-pull: |
    #   cat > asound.conf <<EOF
    #   pcm.!default {
    #     type pulse
    #     fallback "sysdefault"
    #     hint {
    #       show on
    #       description "Default ALSA Output (currently PulseAudio Sound Server)"
    #     }
    #   }
    #   ctl.!default {
    #     type pulse
    #     fallback "sysdefault"
    #   }
    #   EOF
    # override-build: |
    #   install -m644 -D -t $SNAPCRAFT_PART_INSTALL/etc asound.conf
    stage-packages:
    - libasound2
    - libasound2-plugins
    - libjack0
    - libpulse0

  # patches:
  #   source: patches
  #   plugin: dump
  #   prime: [msm-skillsdir.diff]

  scripts:
    source: scripts
    source-type: local
    plugin: dump
    organize:
      mycroft-launch: bin/mycroft-launch
      sudo: usr/bin/sudo
    stage:
    - bin/mycroft-launch
    - usr/bin/sudo

  desktop:
    source: desktop
    plugin: dump
    organize:
      mycroft.desktop: usr/share/applications/mycroft.desktop
      mycroft.png: usr/share/icons/mycroft.png

  snapcraft-preload:
    # Until sergiusens/snapcraft-preload#29 is merged
    source: https://github.com/diddledan/snapcraft-preload.git
    source-branch: semaphore-support
    plugin: cmake
    build-packages:
    - try:
      - gcc-multilib
      - g++-multilib
    stage-packages:
    - try:
      - lib32stdc++6

  # mimic:
  #   after: [patches]
  #   plugin: autotools
  #   source: https://github.com/MycroftAI/mimic.git
  #   source-type: git
  #   source-depth: 1
  #   configflags:
  #   - --prefix=/usr
  #   - --disable-static
  #   - --with-audio=pulseaudio
  #   override-pull: |
  #     snapcraftctl pull
  #     patch -Np1 < $SNAPCRAFT_STAGE/mimic-pulseaudio.diff
  #   build-packages:
  #   - libpcre2-dev
  #   - libpulse-dev
  #   stage-packages:
  #   - libpcre2-8-0
  #   - libpulse0
  #   prime:
  #   - usr/bin
  #   - usr/include
  #   - usr/lib
  #   - -usr/lib/*.a
  #   - -usr/lib/*.la
  #   - -usr/lib/pkgconfig
  #   - usr/share/mimic

  mycroft-conf:
    plugin: nil
    override-pull: |
      cat <<EOF > mycroft.conf
      {
        "enclosure": {
          "platform": "snap",
          "update": "true"
        }
      }
      EOF
    override-build:
      install -m644 -D -t $SNAPCRAFT_PART_INSTALL/etc/mycroft mycroft.conf

  mycroft-deps:
    plugin: nil
    override-stage: |
      snapcraftctl stage
      sed -i -E 's|(/usr/lib/x86_64-linux-gnu/libc_nonshared.a)|/snap/mycroft/current/\1|' \
        $SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libc.so
      sed -i -E 's|(/usr/lib/x86_64-linux-gnu/libmvec_nonshared.a)|/snap/mycroft/current/\1|' \
        $SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libm.so
      sed -i -E 's|(/usr/lib/x86_64-linux-gnu/libpthread_nonshared.a)|/snap/mycroft/current/\1|' \
        $SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpthread.so
    organize:
      usr/lib/*/*fann*.so*: usr/lib/
      usr/bin/mpg123.bin: usr/bin/mpg123
    stage-packages:
    - libgdk-pixbuf2.0-0 # yad
    - libgtk-3-0         # yad
    - libfreetype6       # yad
    - libfontconfig1     # yad
    - libnotify4         # yad
    - libnotify-bin
    - yad
    - binutils
    - bison
    - cmake
    - curl
    - flac
    - g++
    - gcc
    - git
    - jq
    - libasound2-dev
    - libasound2-plugins
    - libc++-dev
    - libc6-dev
    - libfann-dev
    - libffi-dev
    - libglib2.0-dev
    - libgpm2
    - libicu-dev
    - libjpeg-dev
    - libpcre2-dev
    - libpulse-dev
    - libssl-dev
    - libvlc-dev
    - locales-all
    - make
    - mpg123
    - mplayer
    - patch
    - pkg-config
    - portaudio19-dev
    - pulseaudio-utils
    - python-gobject-2-dev
    - python-setuptools
    - python3-dev
    - rsync
    - swig
    - vlc
    - zlib1g

  mycroft:
    after: [snapcraft-preload]
    source: https://github.com/MycroftAI/mycroft-core.git
    source-type: git
    plugin: nil
    override-pull: |
      snapcraftctl pull
      git checkout "$(git describe --tags --abbrev=0 --match release/v*)"
      snapcraftctl set-version "$(git describe --tags | sed -e 's|release/v||')"
      # patch -Np1 -i "$SNAPCRAFT_STAGE/mycroft-cache.diff"
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/opt/mycroft
      rsync -a ./ $SNAPCRAFT_PART_INSTALL/opt/mycroft/
    stage-packages:
    - libgdk-pixbuf2.0-0 # yad
    - libgtk-3-0         # yad
    - libfreetype6       # yad
    - libfontconfig1     # yad
    - libnotify4         # yad
    - yad
    - autoconf
    - automake
    - bison
    - build-essential
    - curl
    - flac
    - git
    - jq
    - libfann-dev
    - libffi-dev
    - libglib2.0-dev
    - libicu-dev
    - libjpeg-dev
    - libssl-dev
    - libtool
    - mpg123
    - pkg-config
    - portaudio19-dev
    - python-gobject-2-dev
    - python-setuptools
    - python3
    - python3-dev
    - screen
    - swig
    prime:
    - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libc.so
    - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libm.so
    - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpthread.so

  # mycroft-plasma:
  #   after: [desktop-qt5]
  #   source: https://anongit.kde.org/plasma-mycroft.git
  #   plugin: cmake
  #   configflags:
  #   - -DCMAKE_INSTALL_PREFIX=/usr
  #   - -DCMAKE_BUILD_TYPE=Release
  #   - -DKDE_INSTALL_LIBDIR=lib
  #   - -DKDE_INSTALL_USE_QT_SYS_PATHS=on
  #   override-build: |
  #     snapcraftctl build
  #     chmod +x usr/share/plasma/plasmoids/org.kde.plasma.mycroftplasmoid/contents/code/*service.sh
