name: mycroft
version: latest
version-script: |
  cat $SNAPCRAFT_STAGE/mycroft-source/.version | sed -e 's|release/v||'
icon: snap/gui/mycroft.png
summary: Your AI personal assistant!
description: >
  Mycroft is a free and open-source intelligent personal assistant and knowledge
  navigator for Linux-based operating systems that uses a natural language user
  interface. It is the world’s first fully open-source AI voice assistant.

  Mycroft is named after a fictional computer from 1966 science fiction novel
  "The Moon Is a Harsh Mistress".

  Installing skills by voice seems to be broken for now, but you can use
  the `mycroft.msm` command to list, install, and remove skills.

grade: stable
confinement: strict

parts:
  alsa:
    after: [alsa-lib, alsa-plugins]
  alsa-lib:
    # configflags needed until LP#1766878 is fixed
    configflags:
    - --prefix=/usr
    - --sysconfdir=/etc
    - --libexec=/usr/lib
    - --libdir=/usr/lib
    - --localstatedir=/var
    - --with-configdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/alsa
    - --with-plugindir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/alsa-lib
    - --disable-alisp
    - --disable-aload
    - --disable-python
    - --disable-rawmidi
    - --disable-static
    - --disable-topology
    - --disable-ucm
    - --enable-symbolic-functions
    prime: ['*']
  alsa-plugins:
    after: [alsa-lib]
    # configflags needed until LP#1766878 is fixed
    configflags:
    - --prefix=/usr
    - --sysconfdir=/etc
    - --libexec=/usr/lib
    - --libdir=/usr/lib
    - --localstatedir=/var
    - --disable-arcamav
    - --disable-avcodec
    - --disable-jack
    - --disable-mix
    - --disable-oss
    - --disable-usbstream
    - --with-plugindir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/alsa-lib
    - --disable-static
    - LDFLAGS=-L$SNAPCRAFT_STAGE/usr/lib
    prime: ['*']

  patches:
    source: patches
    plugin: dump
    prime:
    - msm-skillsdir.diff
    - mycroft-cache.diff

  scripts:
    source: scripts
    source-type: local
    plugin: dump
    override-pull: |
      snapcraftctl pull
      chmod +x mycroft-launch
    organize:
      mycroft-launch: bin/mycroft-launch

  mimic:
    after: [patches]
    plugin: autotools
    source: https://github.com/MycroftAI/mimic.git
    source-depth: 1
    configflags:
    - --prefix=/usr
    - --disable-static
    - --with-audio=pulseaudio
    override-pull: |
      snapcraftctl pull
      patch -Np1 < $SNAPCRAFT_STAGE/mimic-pulseaudio.diff
    build-packages:
    - libpcre2-dev
    - libpulse-dev
    stage-packages:
    - libpcre2-8-0
    - libpulse0

  portaudio:
    after: [alsa]
    source: http://www.portaudio.com/archives/pa_stable_v190600_20161030.tgz
    plugin: cmake
    configflags:
    - -DCMAKE_INSTALL_PREFIX=/usr
    - -DPA_USE_ALSA=ON
    - -DPA_USE_JACK=ON
    build-packages:
    - libjack-dev
    stage-packages:
    - libjack0

  mpg123:
    after: [alsa]
    source: http://sourceforge.mirrorservice.org/m/mp/mpg123/mpg123/1.25.10/mpg123-1.25.10.tar.bz2
    plugin: autotools
    configflags:
    - --prefix=/usr
    - --disable-static
    - --with-default-audio=pulse
    build-packages:
    - libpulse-dev
    stage-packages:
    - libpulse0

  vlc:
    after: [alsa, mpg123, portaudio]
    source: https://download.videolan.org/pub/videolan/vlc/3.0.3/vlc-3.0.3.tar.xz
    source-checksum: sha256/9ba8b04bdb13f7860a2041768ac83b47b397a36549c71c530b94028a3cfd5b51
    plugin: autotools
    override-pull: |
      snapcraftctl pull
      sed -i 's|0\.19\.8|0\.19\.7|'  configure.ac
    override-build: |
      cd extras/tools
      ./bootstrap
      make -j$SNAPCRAFT_PARALLEL_BUILD_COUNT .protoc
      # make -j$SNAPCRAFT_PARALLEL_BUILD_COUNT .nasm
      cd ../../
      export PATH=$PWD/extras/tools/build/bin:$PATH
      cd contrib && mkdir linux && cd linux
      ../bootstrap \
        --disable-a52 \
        --disable-chromaprint \
        --disable-dca \
        --disable-disc \
        --disable-ebml \
        --disable-fluid \
        --disable-fontconfig \
        --disable-freetype2 \
        --disable-gettext \
        --disable-glib \
        --disable-gnutls \
        --disable-gpg-error \
        --disable-jack \
        --disable-jpeg \
        --disable-libdsm \
        --disable-libxml2 \
        --disable-lua \
        --disable-matroska \
        --disable-mfx \
        --disable-modplug \
        --disable-mpcdec \
        --disable-mpg123 \
        --disable-mysofa \
        --disable-ncurses \
        --disable-png \
        --disable-qt \
        --disable-srt \
        --disable-tiff \
        --disable-tiger \
        --disable-tremor \
        --disable-upnp \
        --disable-vncclient \
        --disable-xcb \
        --disable-xcb-proto \
        --disable-xorg-macros \
        --disable-xproto \
        --disable-zlib \
        --disable-zvbi
      make -j$SNAPCRAFT_PARALLEL_BUILD_COUNT fetch
      make -j$SNAPCRAFT_PARALLEL_BUILD_COUNT
      make install
      cd ../../
      ./configure \
        --prefix=$SNAPCRAFT_PART_INSTALL/usr \
        --enable-merge-ffmpeg \
        --disable-a52
      make -j$SNAPCRAFT_PARALLEL_BUILD_COUNT
      make install
    build-packages:
    - ant
    - autoconf
    - automake
    - bison
    - build-essential
    - cmake
    - curl
    - flex
    - g++
    - gettext
    - git
    - libavahi-client-dev
    - libcdio-dev
    - libdbus-1-dev
    - libdirectfb-dev
    - libebml-dev
    - libfreerdp-dev
    - libfreetype6-dev
    - libfribidi-dev
    - libglib2.0-dev
    - libgnutls28-dev
    - libidn11-dev
    - libjpeg8-dev
    - libjack-dev
    - liblircclient-dev
    - liblua5.2-dev
    - libmatroska-dev
    - libmtp-dev
    - libncursesw5-dev
    - libpng-dev
    - libpulse-dev
    - librsvg2-dev
    - libsecret-1-dev
    - libtool
    - libtool-bin
    - libudev-dev
    - libupnp-dev
    - libv4l-dev
    - libva-dev
    - libvdpau-dev
    - libwayland-dev
    - libx11-dev
    - libxcb-composite0-dev
    - libxcb-keysyms1-dev
    - libxcb-randr0-dev
    - libxcb-shm0-dev
    - libxcb-xfixes0-dev
    - libxcb-xv0-dev
    - libxcb1-dev
    - libxext-dev
    - libxi-dev
    - libxinerama-dev
    - libxkbcommon-x11-dev
    - libxml2-dev
    - libxpm-dev
    - libzvbi-dev
    - lua5.2
    - make
    - pkg-config
    - ragel
    - wayland-protocols
    - xz-utils
    - yasm
    - zlib1g-dev
    stage-packages:
    - breeze-icon-theme
    - dbus-x11
    - fonts-freefont-ttf
    - frameworkintegration
    - libebml4v5
    - libfreerdp-client1.1
    - libfreerdp-core1.1
    - libfreerdp-gdi1.1
    - libfreetype6
    - libfribidi0
    - libgcc1
    - libglib2.0-0
    - libjack0
    - libjpeg8
    - liblua5.2-0
    - libmatroska6v5
    - libmtp9
    - libnotify4
    - libpulse0
    - librsvg2-2
    - libschroedinger-1.0-0
    - libsecret-1-0
    - libupnp6
    - libva-drm1
    - libva-x11-1
    - libva1
    - libvdpau1
    - libwayland-client0
    - libx11-6
    - libxcb-composite0
    - libxcb-keysyms1
    - libxcb-randr0
    - libxcb-shm0
    - libxcb-xv0
    - libxcb1
    - libxext6
    - libxi6
    - libxinerama1
    - libxkbcommon-x11-0
    - libxpm4
    - libzvbi0
    - mesa-utils
    - mesa-vdpau-drivers
    - vdpau-va-driver
    - zlib1g

  mycroft-deps:
    after:
    - alsa
    - mimic
    - mpg123
    - patches
    - portaudio
    - vlc
    plugin: nil
    stage-packages:
    - libgdk-pixbuf2.0-0 # yad
    - libgtk-3-0         # yad
    - libfreetype6       # yad
    - libfontconfig1     # yad
    - libnotify4         # yad
    - libnotify-bin
    - yad
    - bison
    - build-essential
    - coreutils
    - curl
    - flac
    - git
    - jq
    - libc6
    - libfann-dev
    - libffi-dev
    - libgcc1
    - libglib2.0-dev
    - libicu-dev
    - libjpeg-dev
    - libpcre3
    - libssl-dev
    - locales-all
    - pulseaudio-utils
    - python-gobject-2-dev
    - python-setuptools
    - python3-dev
    - rsync
    - swig
    - zlib1g

  mycroft:
    source: https://github.com/MycroftAI/mycroft-core.git
    plugin: dump
    override-pull: |
      snapcraftctl pull
      git checkout $(git describe --tags --abbrev=0 --match release/v*)
      git describe --tags > .version
    organize:
      '*': mycroft-source/
      '.*.yml': mycroft-source/
      '.coveralls': mycroft-source/.coveralls
      '.version': mycroft-source/.version
      '.git*': mycroft-source/

apps:
  mycroft:
    command: alsa-launch mycroft-launch start-all
    plugs:
    - desktop
    - desktop-legacy
    - network
    - network-bind
    - pulseaudio
    - x11
    - wayland

  msm:
    command: mycroft-launch python3 "$SNAP_USER_COMMON/mycroft/.venv/bin/msm"
    plugs:
    - desktop
    - desktop-legacy
    - network
    - network-bind
    - pulseaudio
    - x11
    - wayland

  cli:
    command: mycroft-launch python3 "$SNAP_USER_COMMON/mycroft/mycroft/client/text/main.py"
    plugs:
    - desktop
    - desktop-legacy
    - network
    - x11
    - wayland

  bus:
    command: mycroft-launch python3 "$SNAP_USER_COMMON/mycroft/mycroft/messagebus/service/main.py"
    plugs:
    - desktop
    - desktop-legacy
    - network
    - network-bind
    - x11
    - wayland

  skills:
    command: mycroft-launch python3 "$SNAP_USER_COMMON/mycroft/mycroft/skills/main.py"
    plugs:
    - desktop
    - desktop-legacy
    - network
    - x11
    - wayland

  audio:
    command: alsa-launch mycroft-launch python3 "$SNAP_USER_COMMON/mycroft/mycroft/audio/main.py"
    plugs:
    - desktop
    - desktop-legacy
    - network
    - pulseaudio
    - x11
    - wayland

  voice:
    command: alsa-launch mycroft-launch python3 "$SNAP_USER_COMMON/mycroft/mycroft/client/speech/main.py"
    plugs:
    - desktop
    - desktop-legacy
    - network
    - pulseaudio
    - x11
    - wayland
